### ISSUE TITLE
Questions model

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#104]
Let's not hard-code the questions as columns on NPO and student applications. Instead, let's have them be models with a polymorphic `belongs_to :questionable` for StudentApplications and NpoApplications.

I think they should also belong_to a semester.

Admins should be able to create, read, update these questions on the admin side and have them show up on the applications. Questions should not be deleted since we might want to review apps from previous semesters.

**Comment by kevinshieh** [comment]
is this still relevant

**Comment by SamLau95** [comment]
Nope. Closing now since we decided to just hard-code questions.
