### ISSUE TITLE
Rework Apply Page

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#117]
@missonederland is on board! She's working on possible redesigns for the apply page (http://calblueprint-new-staging.herokuapp.com/apply)

**Comment by missonederland** [comment]
![apply v1 5](https://cloud.githubusercontent.com/assets/5771544/7425913/12dadb42-ef6f-11e4-9f1a-cb7f9a0c6d91.png)
![apply v1](https://cloud.githubusercontent.com/assets/5771544/7425914/12f7211c-ef6f-11e4-8684-06cb9aa9c3a6.png)
![apply v2](https://cloud.githubusercontent.com/assets/5771544/7425915/1301853a-ef6f-11e4-8077-8cea72769510.png)

**Comment by noahsark769** [comment]
I am a big fan of the last one!

**Comment by SamLau95** [comment]
@vivekraghuram any thoughts? :)

**Comment by vivekraghuram** [comment]
I like the last one
