### ISSUE TITLE
redesign Login page for 1) email+pw; and 2) fb+google

### ISSUE THREAD

**Issue by missonederland** [calblueprint/calblueprint.org#131]
![login email](https://cloud.githubusercontent.com/assets/5771544/7427727/aa1ed7de-ef96-11e4-9537-e5d5f74d780e.png)
![login social](https://cloud.githubusercontent.com/assets/5771544/7427728/aa30f8a6-ef96-11e4-8305-600cf1282033.png)

**Comment by SamLau95** [comment]
Yay for gears! @vivekraghuram any feedback?
