### ISSUE TITLE
redesign Team page

### ISSUE THREAD

**Issue by missonederland** [calblueprint/calblueprint.org#133]
![about_team_default](https://cloud.githubusercontent.com/assets/5771544/7429819/87027504-efbd-11e4-975b-4410539c86b6.png)
![about_team_click](https://cloud.githubusercontent.com/assets/5771544/7429820/8839a078-efbd-11e4-8478-818c0f4b7aef.png)

**Comment by chenhoward** [comment]
I actually like the original card flip better, it just seemed more well contained.
