### ISSUE TITLE
NPO apps should be able to be deleted.

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#183]

**Comment by SamLau95** [comment]
@chenhoward @wonjun This is pretty easy and up for grabs too!

**Comment by chenhoward** [comment]
NOW MINE SQUAD!  I'll try to get this through by tmmr night

**Comment by noahsark769** [comment]
I came here to give a @chenhoward++ for that enthusiasm doe

**Comment by chenhoward** [comment]
LOL thanks @noahsark769 !  I would be doing it right now but I'm trying to push some features for the Rails Decal

**Comment by chenhoward** [comment]
Actually what's the front end process of going about this?  I don't think there is a show view or anything like that for a npo to see their submitted applications

**Comment by SamLau95** [comment]
Just add a button to the admin NPO index that deletes an app (for test NPO apps, for example)

**Comment by chenhoward** [comment]
Oh I totally didn't realize it was suppose to be the admin view I was just looking at the regular controller!

**Comment by SamLau95** [comment]
My bad! Shoulda made this clear.
