### ISSUE TITLE
Code Home Page

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#39]

**Comment by SamLau95** [comment]
Andy's mockup!

[calblueprint_mockup.pdf | uploaded via ZenHub](https://files.zenhub.io/54f3ea5ede8d4ef35f2ad4ef)

[calblueprint_mockup.pdf | uploaded via ZenHub](https://files.zenhub.io/54f3ea63de8d4ef35f2ad4f0)

**Comment by jryoo** [comment]
I hope not just a software shop ;).
