### ISSUE TITLE
Log in with FB and Google

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#55]
As part of the application process.

**Comment by vivekraghuram** [comment]
Do you think Google is enough? Everybody has a gmail cause of Bmail. Just to save work.

**Comment by SamLau95** [comment]
Yeah I think Google will be enough - I'll start with that and see if adding Facebook is too much extra work.

**Comment by SamLau95** [comment]
Done in #71 . Use `applicant_omniauth_authorize_path :facebook` or `:google_oauth2` in the app.
