### ISSUE TITLE
Iterate on Students Apply Info page

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#61]
http://calblueprint-new-staging.herokuapp.com/apply/students

**Comment by lixonic** [comment]
with that banner image, the Apply Now button background seems subtle.  background on :hover seems better

**Comment by vivekraghuram** [comment]
I got this. Any feedback?

**Comment by SamLau95** [comment]
I think @lixonic 's comment is valid. Also the page starting from application process down feels a little text-heavy; any thoughts?
