### ISSUE TITLE
Iterate on NPO apply info page

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#62]

**Comment by vivekraghuram** [comment]
I got this too! Any feedback?

**Comment by SamLau95** [comment]
I think the picture makes the black text hard to see, but I'm not sure whether you want to use that image in the end anyway.

Maybe try putting a semi-transparent gradient on top? I did that for the background at http://ros-staging.herokuapp.com/

**Comment by SamLau95** [comment]
Maybe a small inset box-shadow for the blue quote section? It feels a bit flat (unless that's what you were going for)

The FAQ here and on the student apply page looks like a lot of text - maybe something like http://refills.bourbon.io/#vertical-tabs would help?
